<?php

add_action( 'acf/include_fields', function() {
    if ( ! function_exists( 'acf_add_local_field_group' ) ) {
        return;
    }

    acf_add_local_field_group( array(
        'key' => 'group_65a54f7c64715',
        'title' => 'Form Settings',
        'fields' => array(
            array(
                'key' => 'field_65a55b1f03e5b',
                'label' => 'Notifications',
                'name' => '',
                'aria-label' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_65a54f7c15d04',
                'label' => 'Email Notification',
                'name' => 'email_notification',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'message' => '',
                'default_value' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
                'ui' => 1,
            ),
            array(
                'key' => 'field_65a54f7c15d04ad',
                'label' => 'Variant Email Notification',
                'name' => 'variant_email_notification',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_65a54f7c15d04',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'message' => '',
                'default_value' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
                'ui' => 1,
            ),
            array(
                'key' => 'field_65a54fdcc2bbe',
                'label' => 'Email Subject',
                'name' => 'email_subject',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => 'Default is form title',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_65a54f7c15d04',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_65a54ffdc2bbf',
                'label' => 'Email Recipients',
                'name' => 'email_recipients',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => 'Separate with commas, default is form site admin.',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_65a54f7c15d04',
                            'operator' => '==',
                            'value' => '1',
                        ),
                        array(
                            'field' => 'field_65a54f7c15d04ad',
                            'operator' => '==',
                            'value' => '0',
                        ),

                    ),
                ),
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),

            array(
                'key' => 'field_65a54ffdc2bbfaf345',
                'label' => 'Form Field',
                'name' => 'email_recipients_form_field',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => 'Give the name of the form field',
                'required' => 1,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_65a54f7c15d04',
                            'operator' => '==',
                            'value' => '1',
                        ),
                        array(
                            'field' => 'field_65a54f7c15d04ad',
                            'operator' => '==',
                            'value' => '1',
                        ),

                    ),
                ),
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),

            array(
                'key' => 'field_65a54ffdc2bbfaf345aregg',
                'label' => 'Email Recipients',
                'name' => 'email_recipients_form_field_value',
                'aria-label' => '',
                'type' => 'textarea',
                'instructions' => 'Separate values with newlines',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_65a54f7c15d04',
                            'operator' => '==',
                            'value' => '1',
                        ),
                        array(
                            'field' => 'field_65a54f7c15d04ad',
                            'operator' => '==',
                            'value' => '1',
                        ),

                    ),
                ),
                'wrapper' => array(
                    'width' => '100',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => 'Department 1 : department1@domain.gr,other@domain.gr' . PHP_EOL . 'Department 2 : department2@domain.gr',
                'prepend' => '',
                'append' => '',
            ),


            array(
                'key' => 'field_65a54f7c15d04ad_thank_you_email',
                'label' => 'Send thank you email',
                'name' => 'send_thank_you_email',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'wrapper' => array(
                    'width' => '100',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'message' => '',
                'default_value' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
                'ui' => 1,
            ),
            array(
                'key' => 'field_65a54fdcc2bbe_thank_you_email_subject',
                'label' => 'Thank you email subject',
                'name' => 'thank_you_email_subject',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => 'Default is form title',
                'required' => 1,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_65a54f7c15d04ad_thank_you_email',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_65a54fdcc2bbe_thank_you_email_field',
                'label' => 'Thank you email field',
                'name' => 'thank_you_email_field',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => 'Default is form title',
                'required' => 1,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_65a54f7c15d04ad_thank_you_email',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_65a55c53cacd3_thank_email_text',
                'label' => 'Thank you email text',
                'name' => 'thank_you_email_text',
                'aria-label' => '',
                'type' => 'wysiwyg',
                'instructions' => 'You can use [data_table] to get the submission data table',
                'required' => 1,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_65a54f7c15d04ad_thank_you_email',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'default_value' => '<h2>Your form was submitted successfully</h2>Thank you for reaching out. We will get back to you as soon as possible.',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
                'delay' => 0,
            ),

            array(
                'key' => 'field_65a55b6d7cc35',
                'label' => 'Messages',
                'name' => '',
                'aria-label' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_65a55c53cacd3',
                'label' => 'Success Message',
                'name' => 'success_message',
                'type' => 'wysiwyg',
                'required' => 1,
                'hide_admin' => 0,
                'default_value' => '<h3>Η φόρμα υποβλήθηκε επιτυχώς</h3>
Σας ευχαριστούμε που επικοινωνήσατε μαζί μας. Θα επανέλθουμε το συντομότερο δυνατόν.',
                'tabs' => 'all',
                'toolbar' => 'headings',
                'media_upload' => 0,
            ),
            array(
                'key' => 'field_65a55daf7960a',
                'label' => 'Error Message',
                'name' => 'error_message',
                'aria-label' => '',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'default_value' => '<h3>Υπήρξε πρόβλημα με την υποβολή της φόρμας σας</h3>',
                'tabs' => 'all',
                'toolbar' => 'headings',
                'media_upload' => 0,
                'delay' => 0,
                'new_lines' => 'wpautop'
            ),
            array(
                'new_lines' => 'wpautop',
                'key' => 'field_65a55c2fcacd2',
                'label' => 'Entries',
                'name' => '',
                'aria-label' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_65a55b827cc36',
                'label' => 'Create entries?',
                'name' => 'create_entries',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => 'When entries are enabled they will be automatically generated with form submissions, with all the submitted field data. View entries for this form',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'hide_admin' => 0,
                'message' => '',
                'default_value' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
                'ui' => 1,
            ),
            array(
                'key' => 'field_65a645315df76',
                'label' => 'Integrations',
                'name' => '',
                'aria-label' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_65a6453e5df77',
                'label' => 'Mailchimp',
                'name' => 'mailchimp_integration',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
                'ui' => 1,
            ),
            array(
                'key' => 'field_65a6455e5df78',
                'label' => 'List',
                'name' => 'mailchimp_list_id',
                'aria-label' => '',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_65a6453e5df77',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(),
                'default_value' => false,
                'return_format' => 'value',
                'multiple' => 0,
                'allow_null' => 0,
                'ui' => 0,
                'ajax' => 0,
                'placeholder' => '',
            ),

        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'iw-form',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ) );
} );
